/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImportarHistoricoRouteImport } from './routes/importar-historico'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContasContaIdRouteImport } from './routes/contas.$contaId'
import { Route as ContasContaIdAnoMesRouteImport } from './routes/contas.$contaId.$ano.$mes'
import { Route as ContasContaIdAnoMesCartaoCartaoIdRouteImport } from './routes/contas.$contaId.$ano.$mes_.cartao.$cartaoId'

const ImportarHistoricoRoute = ImportarHistoricoRouteImport.update({
  id: '/importar-historico',
  path: '/importar-historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasContaIdRoute = ContasContaIdRouteImport.update({
  id: '/$contaId',
  path: '/$contaId',
  getParentRoute: () => ContasRoute,
} as any)
const ContasContaIdAnoMesRoute = ContasContaIdAnoMesRouteImport.update({
  id: '/$ano/$mes',
  path: '/$ano/$mes',
  getParentRoute: () => ContasContaIdRoute,
} as any)
const ContasContaIdAnoMesCartaoCartaoIdRoute =
  ContasContaIdAnoMesCartaoCartaoIdRouteImport.update({
    id: '/$ano/$mes_/cartao/$cartaoId',
    path: '/$ano/$mes/cartao/$cartaoId',
    getParentRoute: () => ContasContaIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/importar': typeof ImportarRoute
  '/importar-historico': typeof ImportarHistoricoRoute
  '/contas/$contaId': typeof ContasContaIdRouteWithChildren
  '/contas/$contaId/$ano/$mes': typeof ContasContaIdAnoMesRoute
  '/contas/$contaId/$ano/$mes/cartao/$cartaoId': typeof ContasContaIdAnoMesCartaoCartaoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/importar': typeof ImportarRoute
  '/importar-historico': typeof ImportarHistoricoRoute
  '/contas/$contaId': typeof ContasContaIdRouteWithChildren
  '/contas/$contaId/$ano/$mes': typeof ContasContaIdAnoMesRoute
  '/contas/$contaId/$ano/$mes/cartao/$cartaoId': typeof ContasContaIdAnoMesCartaoCartaoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/importar': typeof ImportarRoute
  '/importar-historico': typeof ImportarHistoricoRoute
  '/contas/$contaId': typeof ContasContaIdRouteWithChildren
  '/contas/$contaId/$ano/$mes': typeof ContasContaIdAnoMesRoute
  '/contas/$contaId/$ano/$mes_/cartao/$cartaoId': typeof ContasContaIdAnoMesCartaoCartaoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/importar'
    | '/importar-historico'
    | '/contas/$contaId'
    | '/contas/$contaId/$ano/$mes'
    | '/contas/$contaId/$ano/$mes/cartao/$cartaoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/importar'
    | '/importar-historico'
    | '/contas/$contaId'
    | '/contas/$contaId/$ano/$mes'
    | '/contas/$contaId/$ano/$mes/cartao/$cartaoId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/importar'
    | '/importar-historico'
    | '/contas/$contaId'
    | '/contas/$contaId/$ano/$mes'
    | '/contas/$contaId/$ano/$mes_/cartao/$cartaoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ImportarRoute: typeof ImportarRoute
  ImportarHistoricoRoute: typeof ImportarHistoricoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/importar-historico': {
      id: '/importar-historico'
      path: '/importar-historico'
      fullPath: '/importar-historico'
      preLoaderRoute: typeof ImportarHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas/$contaId': {
      id: '/contas/$contaId'
      path: '/$contaId'
      fullPath: '/contas/$contaId'
      preLoaderRoute: typeof ContasContaIdRouteImport
      parentRoute: typeof ContasRoute
    }
    '/contas/$contaId/$ano/$mes': {
      id: '/contas/$contaId/$ano/$mes'
      path: '/$ano/$mes'
      fullPath: '/contas/$contaId/$ano/$mes'
      preLoaderRoute: typeof ContasContaIdAnoMesRouteImport
      parentRoute: typeof ContasContaIdRoute
    }
    '/contas/$contaId/$ano/$mes_/cartao/$cartaoId': {
      id: '/contas/$contaId/$ano/$mes_/cartao/$cartaoId'
      path: '/$ano/$mes/cartao/$cartaoId'
      fullPath: '/contas/$contaId/$ano/$mes/cartao/$cartaoId'
      preLoaderRoute: typeof ContasContaIdAnoMesCartaoCartaoIdRouteImport
      parentRoute: typeof ContasContaIdRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ImportarRoute: ImportarRoute,
  ImportarHistoricoRoute: ImportarHistoricoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
